<?php
/**
 * AttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Meli
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Meli;

use PHPUnit\Framework\TestCase;

/**
 * AttributesTest Class Doc Comment
 *
 * @category    Class
 * @description Attributes
 * @package     Meli
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AttributesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Attributes"
     */
    public function testAttributes()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "value_id"
     */
    public function testPropertyValueId()
    {
    }

    /**
     * Test attribute "value_name"
     */
    public function testPropertyValueName()
    {
    }

    /**
     * Test attribute "value_struct"
     */
    public function testPropertyValueStruct()
    {
    }

    /**
     * Test attribute "values"
     */
    public function testPropertyValues()
    {
    }

    /**
     * Test attribute "attribute_group_id"
     */
    public function testPropertyAttributeGroupId()
    {
    }

    /**
     * Test attribute "attribute_group_name"
     */
    public function testPropertyAttributeGroupName()
    {
    }
}
