<?php
/**
 * ItemsHealthApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Meli
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Meli;

use \Meli\Configuration;
use \Meli\ApiException;
use \Meli\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ItemsHealthApiTest Class Doc Comment
 *
 * @category Class
 * @package  Meli
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ItemsHealthApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for itemsIdHealthActionsGet
     *
     * Return item health actions by id..
     *
     */
    public function testItemsIdHealthActionsGet()
    {
    }

    /**
     * Test case for itemsIdHealthGet
     *
     * Return health by id..
     *
     */
    public function testItemsIdHealthGet()
    {
    }

    /**
     * Test case for sitesSiteIdHealthLevelsGet
     *
     * Return health levels..
     *
     */
    public function testSitesSiteIdHealthLevelsGet()
    {
    }
}
